In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
#Array of zeroes
a=np.zeros((3,3))
print(a)

#Array of ones
b=np.ones((3,2))
print(b)

#Array of constants
c=np.full((3,2),5)
print(c)

#Identity Matrix
d=np.eye(4)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
#RandomMatrix
a=np.random.random((3,2))
print(a)

[[0.21821377 0.01729159]
 [0.9844186  0.93281617]
 [0.6333796  0.62245418]]


In [13]:
#get the second column of a which is the random matrix
print(a[:,0])#slicing

[0.21821377 0.9844186  0.6333796 ]


In [14]:
a[1,1:]=2
print(a)

[[0.21821377 0.01729159]
 [0.9844186  2.        ]
 [0.6333796  0.62245418]]


In [23]:
z=np.zeros((3,3),dtype=np.int64)#changing the datatype from float 64 to int 64
print(z)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [25]:
print(z.dtype)

int64


In [27]:
#Mathemitcal Operations
a=np.array([[1,2],[3,4]])
b=np.array([[5,7],[8,9]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 7]
 [8 9]]


In [28]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 6  9]
 [11 13]]
[[-4 -5]
 [-5 -5]]
[[ 5 14]
 [24 36]]
[[0.2        0.28571429]
 [0.375      0.44444444]]


In [29]:
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [30]:
print(np.dot(a,b))

[[21 25]
 [47 57]]


In [31]:
#Multiplication(Dot Product of vectors)
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.dot(a,b))

30


In [32]:
print(sum(a))

10


In [34]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [36]:
print(np.sum(x,axis=0))#gives the sum along the columns individually

[4 6]


In [37]:
#Stacking of arrays
print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [40]:
print(np.stack((a,b),axis=1))

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [41]:
#IMPORTANT

In [42]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [44]:
np.random.shuffle(a)
print(a)

[ 9  8  6 11 10  5  7 13 14 12]


In [45]:
a=np.random.randn(2,3)
print(a)

[[ 0.52921231  2.26217293  0.81942081]
 [-0.17440158 -0.12348997 -0.17428551]]


In [48]:
a=np.random.randint(100,200,8)
print(a)

[152 119 109 188 167 130 136 168]


In [49]:
ele=np.random.choice(a)
print(ele)

136


In [57]:
a=np.array([1,2,5,6,8])
print(np.mean(a))
print(np.median(a))

#Weights
w=np.array([1,4,6,7,2])
print(np.average(a,weights=w))


#Standard deviation
avg=np.mean(a)
sd=np.sqrt(np.mean(abs(avg-a)**2))
print(sd)

#Inbuilt Function
print(np.std(a))

#Variance
print(sd**2)
print(np.var(a))


4.4
5.0
4.85
2.5768197453450252
2.5768197453450252
6.640000000000001
6.640000000000001
